package com.tasnetwork.calibration.energymeter.constant;

public class ConstantRefStdConfig {


	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_1 = 10.0f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_2 = 7.5f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_3 = 5.0f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_4 = 4.0f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_5 = 2.5f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_6 = 1.0f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_7 = 0.5f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_8 = 0.4f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_9 = 0.25f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_10 = 0.1f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_11 = 0.05f;
	public static float RSS_HTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_12 = 0.01f;

	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_1    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_2    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_3    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_4    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_5    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_6    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_7    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_8    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_9    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_10    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_11    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_12    = "100000000";
	public static String RSS_HTCT_ACTIVE_PULSE_CONSTANT_BELOW_LEVEL_12             = "100000000";
	
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_1  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_2  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_3  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_4  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_5  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_6  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_7  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_8  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_9  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_10  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_11  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_12  = "100000000";
	public static String RSS_HTCT_REACTIVE_PULSE_CONSTANT_BELOW_LEVEL_12           = "100000000";
	
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_1 = 10.0f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_2 = 7.5f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_3 = 5.0f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_4 = 4.0f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_5 = 2.5f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_6 = 1.0f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_7 = 0.5f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_8 = 0.4f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_9 = 0.25f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_10 = 0.1f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_11 = 0.05f;
	public static float RSS_LTCT_CURRENT_THRESHOLD_IN_AMPS_LEVEL_12 = 0.01f;
	
	public static float RSS_LTCT_VOLTAGE_THRESHOLD_IN_AMPS_LEVEL_1 = 480.0f;
	public static float RSS_LTCT_VOLTAGE_THRESHOLD_IN_AMPS_LEVEL_2 = 240.0f;
	public static float RSS_LTCT_VOLTAGE_THRESHOLD_IN_AMPS_LEVEL_3 = 120.0f;
	public static float RSS_LTCT_VOLTAGE_THRESHOLD_IN_AMPS_LEVEL_4 = 60.0f;
	

	
	
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_1    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_2    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_3    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_4    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_5    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_6    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_7    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_8    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_9    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_10    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_11    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_ABOVE_LEVEL_12    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_BELOW_OR_EQUAL_LEVEL_4_CURRENT_BELOW_OR_EQUAL_LEVEL_12             = "100000000";
	
	
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_1    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_2    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_3    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_4    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_5    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_6    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_7    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_8    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_9    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_10    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_11    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_ABOVE_LEVEL_12    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_4_CURRENT_BELOW_OR_EQUAL_LEVEL_12             = "100000000";
	
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_1    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_2    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_3    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_4    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_5    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_6    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_7    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_8    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_9    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_10    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_11    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_ABOVE_LEVEL_12    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_3_CURRENT_BELOW_OR_EQUAL_LEVEL_12             = "100000000";
	
	
	
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_1    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_2    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_3    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_4    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_5    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_6    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_7    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_8    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_9    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_10    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_11    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_ABOVE_LEVEL_12    = "100000000";
	public static String RSS_LTCT_ACTIVE_PULSE_CONSTANT_VOLT_ABOVE_LEVEL_2_CURRENT_BELOW_OR_EQUAL_LEVEL_12             = "100000000";
	
	
	
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_1  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_2  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_3  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_4  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_5  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_6  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_7  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_8  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_9  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_10  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_11  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_ABOVE_OR_EQUAL_LEVEL_12  = "100000000";
	public static String RSS_LTCT_REACTIVE_PULSE_CONSTANT_BELOW_LEVEL_12           = "100000000";
}
